# Generated by Django 6.0.7 on 2026-07-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('registry', '0001_initial'),
        ('resources', '0002_ressource_valeur_unitaire'),
        ('tasks', '0001_initial'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stock_critique', 'Stock critique'), ('stock_a_surveiller', 'Stock à surveiller'), ('facture_impayee', 'Facture impayée'), ('tache_en_retard', 'Tâche en retard'), ('consommation_elevee', 'Consommation élevée')], max_length=40)),
                ('niveau', models.CharField(choices=[('critique', 'Critique'), ('elevee', 'Élevée'), ('moderee', 'Modérée')], max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('traitee', 'Traitée'), ('ignoree', 'Ignorée')], default='active', max_length=20)),
                ('date_declenchement', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('entite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='registry.entite')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='treasury.facture')),
                ('ressource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='resources.ressource')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertes', to='core.secteur')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='tasks.tache')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alerte',
                'ordering': ['-date_declenchement'],
                'indexes': [models.Index(fields=['secteur'], name='alerte_secteur_d6ca2a_idx'), models.Index(fields=['statut'], name='alerte_statut_22029f_idx'), models.Index(fields=['niveau'], name='alerte_niveau_f1639a_idx'), models.Index(fields=['type'], name='alerte_type_bc0125_idx')],
            },
        ),
    ]
