# Generated by Django 6.0.7 on 2026-07-25 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(blank=True, max_length=60)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=10)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='a_faire', max_length=20)),
                ('lieu', models.CharField(blank=True, max_length=150)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_creees', to=settings.AUTH_USER_MODEL)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches', to='core.secteur')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'db_table': 'tache',
                'ordering': ['echeance', '-priorite'],
            },
        ),
        migrations.CreateModel(
            name='TacheHistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='tasks.tache')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'db_table': 'tache_historique_statut',
                'ordering': ['-date_changement'],
            },
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['secteur'], name='tache_secteur_4fc9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['statut'], name='tache_statut_dca59e_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['echeance'], name='tache_echeanc_f77054_idx'),
        ),
    ]
