# Generated by Django 5.1.15 on 2026-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
