# Generated by Django 6.1.1 on 2026-09-16 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_parametresysteme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_invitation_crees', to=settings.AUTH_USER_MODEL)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_invitation', to='core.secteur')),
            ],
            options={
                'verbose_name': "Code d'invitation",
                'verbose_name_plural': "Codes d'invitation",
                'db_table': 'code_invitation',
            },
        ),
        migrations.CreateModel(
            name='TokenVerificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('date_expiration', models.DateTimeField()),
                ('utilise_le', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_verification_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Token de vérification d'email",
                'verbose_name_plural': "Tokens de vérification d'email",
                'db_table': 'token_verification_email',
            },
        ),
    ]
