# Generated by Django 5.1.15 on 2026-09-28 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_codeinvitation_tokenverificationemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenReinitialisationMotDePasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('date_expiration', models.DateTimeField()),
                ('utilise_le', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_reinitialisation_mdp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de réinitialisation de mot de passe',
                'verbose_name_plural': 'Tokens de réinitialisation de mot de passe',
                'db_table': 'token_reinitialisation_mot_de_passe',
            },
        ),
    ]
