# Generated by Django 6.0.7 on 2026-07-25 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('champs_dynamiques', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entites_creees', to=settings.AUTH_USER_MODEL)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entites', to='core.secteur')),
            ],
            options={
                'verbose_name': 'Entité',
                'verbose_name_plural': 'Entités',
                'db_table': 'entite',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['secteur'], name='entite_secteur_2e3d81_idx'), models.Index(fields=['type'], name='entite_type_a0fd51_idx'), models.Index(fields=['statut'], name='entite_statut_4f01d9_idx')],
            },
        ),
    ]
