# Generated by Django 6.0.7 on 2026-07-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entite',
            name='numero_fiscal',
            field=models.CharField(blank=True, help_text="Numéro d'identification fiscale (NIU) de l'entité, si applicable.", max_length=50),
        ),
        migrations.AddField(
            model_name='entite',
            name='numero_rccm',
            field=models.CharField(blank=True, help_text='Numéro RCCM (Registre du Commerce et du Crédit Mobilier), pour les entités professionnelles.', max_length=50),
        ),
    ]
