# Generated by Django 5.1.15 on 2026-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_entite_numero_fiscal_entite_numero_rccm'),
    ]

    operations = [
        migrations.AddField(
            model_name='entite',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
