# Generated by Django 6.0.7 on 2026-07-25 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('nom', models.CharField(max_length=200)),
                ('unite', models.CharField(blank=True, max_length=30)),
                ('niveau_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('seuil_critique', models.DecimalField(decimal_places=2, max_digits=14)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statut', models.CharField(choices=[('critique', 'Critique'), ('a_surveiller', 'À surveiller'), ('stable', 'Stable')], default='stable', editable=False, max_length=20)),
                ('emplacement', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_creees', to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='registry.entite')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ressources', to='core.secteur')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'db_table': 'ressource',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['secteur'], name='ressource_secteur_58d094_idx'), models.Index(fields=['statut'], name='ressource_statut_41f817_idx'), models.Index(fields=['type'], name='ressource_type_294b62_idx')],
            },
        ),
    ]
