# Generated by Django 6.0.7 on 2026-07-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_ressource_valeur_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='seuil_alerte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='seuil_critique',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
