# Generated by Django 5.1.15 on 2026-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_ressource_seuil_alerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
