# Generated by Django 6.0.7 on 2026-07-25 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
                'db_table': 'secteur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSectorielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelles', models.JSONField(blank=True, default=dict)),
                ('seuils', models.JSONField(blank=True, default=dict)),
                ('regles', models.JSONField(blank=True, default=dict)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('secteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='core.secteur')),
            ],
            options={
                'verbose_name': 'Configuration sectorielle',
                'verbose_name_plural': 'Configurations sectorielles',
                'db_table': 'configuration_sectorielle',
            },
        ),
    ]
