# Generated by Django 6.0.7 on 2026-07-31 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100)),
                ('valeur', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='core.secteur')),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
                'db_table': 'parametre_systeme',
                'constraints': [models.UniqueConstraint(fields=('cle', 'secteur'), name='uq_parametre_cle_secteur')],
            },
        ),
    ]
