# Generated by Django 5.1.15 on 2026-09-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parametresysteme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleIdempotence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=64)),
                ('methode', models.CharField(max_length=10)),
                ('chemin', models.CharField(max_length=255)),
                ('empreinte_corps', models.CharField(max_length=64)),
                ('statut_http', models.PositiveSmallIntegerField()),
                ('corps_reponse', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cles_idempotence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cle_idempotence',
                'indexes': [models.Index(fields=['date_creation'], name='cle_idempot_date_cr_46c4b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'cle'), name='uniq_idempotence_utilisateur_cle')],
            },
        ),
    ]
