# Generated by Django 5.1.15 on 2026-09-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cleidempotence'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteur',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
    ]
