# Generated by Django 6.0.7 on 2026-07-25 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('registry', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('mouvement_stock', 'Mouvement de stock')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('date_transaction', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='registry.entite')),
                ('ressource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='resources.ressource')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.secteur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statut', models.CharField(choices=[('emise', 'Émise'), ('payee', 'Payée'), ('impayee', 'Impayée'), ('relancee', 'Relancée'), ('annulee', 'Annulée')], default='emise', max_length=20)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_derniere_relance', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='registry.entite')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='core.secteur')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='treasury.transaction')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'facture',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['secteur'], name='transaction_secteur_76e799_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='transaction_type_d14ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-date_transaction'], name='transaction_date_tr_308bc4_idx'),
        ),
    ]
