# Generated by Django 6.0.7 on 2026-07-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Taux de TVA en pourcentage, saisi par l'utilisateur (ex. 18.00). Laisser vide si non applicable.", max_digits=5, null=True),
        ),
    ]
