# Generated by Django 6.0.7 on 2026-07-31 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_facture_taux_tva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('mobile_money', 'Mobile money'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='DeclarationConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('especes_superieur_seuil', 'Paiement en espèces au-delà du seuil légal'), ('signalement_manuel', 'Signalement manuel (opération jugée suspecte)')], max_length=30)),
                ('seuil_applique', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('statut', models.CharField(choices=[('a_declarer', 'À déclarer'), ('declaree', 'Déclarée'), ('exemptee', 'Exemptée (justifiée)')], default='a_declarer', max_length=20)),
                ('reference_declaration', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('date_declaration', models.DateTimeField(blank=True, null=True)),
                ('declarant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_effectuees', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_conformite', to='treasury.transaction')),
            ],
            options={
                'verbose_name': 'Déclaration de conformité',
                'verbose_name_plural': 'Déclarations de conformité',
                'db_table': 'declaration_conformite',
                'ordering': ['-date_detection'],
                'indexes': [models.Index(fields=['statut'], name='declaration_statut_8d9d78_idx')],
            },
        ),
    ]
