# Generated by Django 5.1.15 on 2026-09-30 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_transaction_mode_paiement_declarationconformite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='annulee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_annulees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='motif_annulation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
