# Generated by Django 5.1.15 on 2026-09-30 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_facture_annulee_par_facture_date_annulation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='avoir_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='treasury.facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='motif_avoir',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contre_ecriture_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contre_ecritures', to='treasury.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='corrigee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_corrigees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_correction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='motif_correction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remplacements', to='treasury.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('contrepassee', 'Contre-passée')], default='validee', max_length=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('emise', 'Émise'), ('payee', 'Payée'), ('impayee', 'Impayée'), ('relancee', 'Relancée'), ('annulee', 'Annulée'), ('avoir', 'Avoir')], default='emise', max_length=20),
        ),
    ]
