# Generated by Django 5.1.15 on 2026-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_facture_avoir_de_facture_motif_avoir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_maj',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_maj',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
