# Generated by Django 6.0.7 on 2026-07-26 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('registry', '0001_initial'),
        ('resources', '0002_ressource_valeur_unitaire'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_algorithme', models.CharField(choices=[('seuil', 'Seuil'), ('scoring_pondere', 'Scoring pondéré'), ('moyenne_mobile', 'Moyenne mobile'), ('regression_lineaire', 'Régression linéaire')], max_length=30)),
                ('categorie', models.CharField(blank=True, max_length=40)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('facteurs', models.JSONField(blank=True, default=dict)),
                ('impact_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confiance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('ignoree', 'Ignorée')], default='en_attente', max_length=20)),
                ('motif_decision', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('decideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_suggestions', to=settings.AUTH_USER_MODEL)),
                ('entite_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='registry.entite')),
                ('ressource_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='resources.ressource')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='core.secteur')),
                ('transaction_resultante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_origine', to='treasury.transaction')),
            ],
            options={
                'verbose_name': 'Suggestion IA',
                'verbose_name_plural': 'Suggestions IA',
                'db_table': 'suggestion',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['secteur'], name='suggestion_secteur_af2088_idx'), models.Index(fields=['statut'], name='suggestion_statut_bd28d0_idx'), models.Index(fields=['type_algorithme'], name='suggestion_type_al_acb15e_idx')],
            },
        ),
    ]
