# Generated by Django 6.0.7 on 2026-07-31 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('module', models.CharField(max_length=40)),
                ('cible_type', models.CharField(blank=True, max_length=40)),
                ('cible_id', models.CharField(blank=True, max_length=40)),
                ('resultat', models.CharField(choices=[('reussi', 'Réussi'), ('avertissement', 'Avertissement'), ('echec', 'Échec')], default='reussi', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journalisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée de journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'journal_audit',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['module'], name='journal_aud_module_70af8a_idx'), models.Index(fields=['auteur'], name='journal_aud_auteur__9740ae_idx'), models.Index(fields=['-date_action'], name='journal_aud_date_ac_c4fe92_idx'), models.Index(fields=['resultat'], name='journal_aud_resulta_ae3978_idx')],
            },
        ),
    ]
