# Generated by Django 6.0.7 on 2026-07-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type_fichier', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('xls', 'XLS')], max_length=10)),
                ('taille_octets', models.BigIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('termine_avec_anomalies', 'Terminé avec anomalies'), ('echec', 'Échec')], default='en_cours', max_length=30)),
                ('mapping_colonnes', models.JSONField(blank=True, default=dict)),
                ('lignes_totales', models.IntegerField(default=0)),
                ('lignes_importees', models.IntegerField(default=0)),
                ('lignes_rejetees', models.IntegerField(default=0)),
                ('rapport_anomalies', models.JSONField(blank=True, default=list)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to=settings.AUTH_USER_MODEL)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='core.secteur')),
            ],
            options={
                'verbose_name': 'Import de fichier',
                'verbose_name_plural': 'Imports de fichiers',
                'db_table': 'import_fichier',
                'ordering': ['-date_import'],
                'indexes': [models.Index(fields=['secteur'], name='import_fich_secteur_a756d2_idx'), models.Index(fields=['statut'], name='import_fich_statut_8abc39_idx')],
            },
        ),
    ]
